name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

permissions:
  contents: write  # Grant write access to deploy contents
  pages: write     # Grant write access to GitHub Pages
  id-token: write  # Grant write access to ID tokens

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publish the entire project directory
