name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

permissions:
  contents: write  # Grant write access to deploy contents
  pages: write     # Grant write access to GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for future use if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify Node.js version if needed

      - name: Install dependencies (for future use if needed)
        run: npm install

      - name: Build project (for future use if needed)
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publish the entire project directory
